Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/cs1210068/./training.py", line 72, in <module>
    glove_embeddings = load_glove_embeddings(glove_file)
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/cs1210068/./training.py", line 61, in load_glove_embeddings
    with open(glove_file, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './glove.6B.100d.txt'
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/cs1210068/./testing.py", line 74, in <module>
    glove_embeddings = load_glove_embeddings(glove_file)
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/cs1210068/./testing.py", line 63, in load_glove_embeddings
    with open(glove_file, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './glove.6B.100d.txt'
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/evaluate_submission.py", line 12, in <module>
    sub_file = [json.loads(x) for x in open(submission_file)]
FileNotFoundError: [Errno 2] No such file or directory: 'cs1210068/predictions_new.jsonl'
